#!/usr/bin/env node
// One product version for add-on + helper.
//   node scripts/set-version.mjs 0.4.0   write it everywhere
//   node scripts/set-version.mjs --check exit 1 if any file disagrees (CI / release)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const rel = (p) => path.join(root, p);
const readJson = (p) => JSON.parse(fs.readFileSync(rel(p), "utf8"));
const writeJson = (p, v) => fs.writeFileSync(rel(p), JSON.stringify(v, null, 2) + "\n");
const VERSION_TS = "shared/src/version.ts";
const versionTs = (v) =>
  `// Generated by scripts/set-version.mjs — the product version, shared by add-on and helper.\nexport const VERSION = "${v}";\n`;

function current() {
  const found = {
    "package.json": readJson("package.json").version,
    "shared/package.json": readJson("shared/package.json").version,
    "mcp-server/package.json": readJson("mcp-server/package.json").version,
    "mcp-server/package.json (shared dep)": readJson("mcp-server/package.json").dependencies["@firefox-mcp/shared"],
    "extension/manifest.json": readJson("extension/manifest.json").version,
    [VERSION_TS]: (fs.readFileSync(rel(VERSION_TS), "utf8").match(/VERSION = "([^"]+)"/) || [])[1],
  };
  return found;
}

const arg = process.argv[2];
if (!arg || arg === "--check") {
  const found = current();
  const want = arg === "--check" && process.argv[3] ? process.argv[3].replace(/^v/, "") : found["package.json"];
  const bad = Object.entries(found).filter(([, v]) => v !== want);
  if (!arg) {
    for (const [f, v] of Object.entries(found)) console.log(`${v}\t${f}`);
  } else if (bad.length) {
    for (const [f, v] of bad) console.error(`version mismatch: ${f} has ${v}, expected ${want}`);
    process.exit(1);
  } else {
    console.log(`all versions are ${want}`);
  }
  process.exit(0);
}

const v = arg.replace(/^v/, "");
if (!/^\d+\.\d+\.\d+$/.test(v)) {
  console.error("usage: set-version.mjs <major.minor.patch> | --check [expected]");
  process.exit(2);
}
for (const p of ["package.json", "shared/package.json", "mcp-server/package.json", "extension/manifest.json"]) {
  const j = readJson(p);
  j.version = v;
  if (j.dependencies?.["@firefox-mcp/shared"]) j.dependencies["@firefox-mcp/shared"] = v;
  writeJson(p, j);
}
fs.writeFileSync(rel(VERSION_TS), versionTs(v));
console.log(`set version ${v} — now run: npm install (refreshes the lockfile)`);
